name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    strategy:
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK with Dependency Caching
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build and test
        run: ./mvnw clean package
