name: release

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up JDK with Dependency Caching
        id: java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Get tag version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: execute a keytool import function
        shell: bash
        run: sudo keytool -importcert -noprompt -trustcacerts -v -alias onerecord -file src/main/resources/onerecord.iata.org.cer -keystore ${{ steps.java.outputs.path }}/lib/security/cacerts -storepass changeit

      - name: Create release artifacts
        run: ./mvnw -Drevision=${{ steps.get_version.outputs.version-without-v }} clean package

      - name: Release without Changelog
        uses: softprops/action-gh-release@v1
        with:
          name: ONE.Record Ontology-DataModel Library ${{ steps.get_version.outputs.version-without-v }}
          files: |
            target/*.jar
